### ISSUE TITLE
Biomarker Entry page for canonical ID

### ISSUE THREAD

**Issue by DaniallMasood** [clinical-biomarkers/biomarker-issue-repo#35]
Need to create an entry page for the most top level Biomarker ID

**Comment by seankim658** [comment]
Once server stuff is done I'll work on the API endpoints for this. However, not going to roll this out until we reset IDs otherwise there will be a lot of dead entries.

**Comment by seankim658** [comment]
Added canonical id to the full search endpoint (currently pushed on dev). We will just need an update to the frontend to have a route like https://biomarkerkb.org/canonical/AN6278 that displays the search results for a call to the the search and list endpoint with a payload like `{"canonical_id": <id>}`. @sujeetvkulkarni whenever you some time. I believe it should be straightforward since we just need a new page route and its reusing everything we already have. Let me know if you have any questions.

**Comment by sujeetvkulkarni** [comment]
@seankim658 can you make changes in the api to look it like
https://api.dev.biomarkerkb.org/biomarker/detail/AN6278
It would be good to have api urls semantic if possible.
I think there is no need to have separate page too.
 https://biomarkerkb.org/biomarker/AN6278 should work just fine.
/biomarker/detail/ api can point to both cases internally.
It would much simpler to have same urls at api and page level.
Also all the same search functionality should work for canonical and non canonical id.

**Comment by seankim658** [comment]
@sujeetvkulkarni That's fine if we want the frontend URL to look like https://biomarkerkb.org/biomarker/AN6278 but I don't think the canonical endpoint should also be under the /biomarker/detail route as it has a fundamentally different return structure. We can handle them both in the /biomarker/detail endpoint but it adds more uncertainty in processing return data as a canonical  id would return a list of biomarkers (same structure as the list endpoint) whereas a second level id would return our data model. I agree that we don't need a new page, but it should re-use the list page, not the detail page. For one canonical id, for example AN6278, there can be multiple biomarkers, i.e. AN6278-1, AN6278-2, etc. 

My thoughts are making a new api route would be more straightforward for the frontend to map the correct API call rather than having to conditionally parse the URL for which data model to expect.

**Comment by sujeetvkulkarni** [comment]
@seankim658 If I understand what you are saying correctly then there is no details page for canonical id only list page? And search interface takes a canonical id and returns list of ids which user can use to go to details page?
So if existing search api is supporting  canonical id to return list id then why we need a separate canonical api/page?

**Comment by seankim658** [comment]
@sujeetvkulkarni  Correct, there won't be a detail page for canonical ids, just a list page where users can view all the biomarkers under that canonical id and then go to the individual detail pages as needed. Raja just wants a semantic URL for sharing/viewing canonical ids since it is an important concept for our biomarker data model. I think in the regular biomarker detail page it might be good to also be able to turn the canonical id value into a link that points to the canonical url:

![image](https://github.com/user-attachments/assets/33620f9f-f748-41e3-86c8-8c356b9108f3)

But the actual page that the canonical url points to will essentially the same as if the user searched a canonical id, like this:

![image](https://github.com/user-attachments/assets/58f284c1-012f-4d5a-8fc3-0d37cae22ebb)

**Comment by sujeetvkulkarni** [comment]
> Added canonical id to the full search endpoint (currently pushed on dev). We will just need an update to the frontend to have a route like https://biomarkerkb.org/canonical/AN6278 that displays the search results for a call to the the search and list endpoint with a payload like `{"canonical_id": <id>}`. @sujeetvkulkarni whenever you some time. I believe it should be straightforward since we just need a new page route and its reusing everything we already have. Let me know if you have any questions.

@seankim658 
So dont we need to make changes on search interface which will add {"canonical_id": <id>} payload. Currently biomarker_id field supports all ids and use current list interface.
In this case maybe we need to add a field (for canonical_id) on different tab so that it will not be used in combination with with other fields.

**Comment by seankim658** [comment]
That sounds fine to me, whatever approach makes more sense from your end.

**Comment by sujeetvkulkarni** [comment]
@seankim658 
I think we can skip search interface changes for now as both search and list apis will need to be part of https://biomarkerkb.org/canonical/AN6278 page, as it needs to be semantic and details page will be acting as a entry point.
I will make changes on biomarker details page from there user will click on canonical id and go to /canonical/AN6278 page - this will be semantic page also user can directly https://biomarkerkb.org/canonical/AN6278 go to link. This page will be modified list page with added search functionality for {"canonical_id": <id>} payload.

**Comment by sujeetvkulkarni** [comment]
@seankim658 I have deployed the changes on dev server please check.

1. Go to https://dev.biomarkerkb.org/biomarker/AN6278-5 page
2. Click on Biomarker Canonical ID link.
3. You will routed to https://dev.biomarkerkb.org/canonical/AN6278 page.
     You can also directly go to https://dev.biomarkerkb.org/canonical/AN6278 page.
     You can use filter, sort like functionality like list page.
      Also then you can click on 'Modify Search' button.
4. Then you will routed to 
     https://dev.biomarkerkb.org/biomarker-search/3cc948866369ae60bd8a87f445f344ff
     page with 'Advanced Search' tab and 'Biomarker ID' field will be filled with 'Biomarker Canonical ID' (AN6278) user 
     started with.
5. User can click on search again then he will routed to normal list page.
    https://dev.biomarkerkb.org/biomarker-list/b77a884d85669d1b2db1a0bc50507c65

**Comment by seankim658** [comment]
Looks good, thanks. Closing.
