### ISSUE TITLE
KG Migration to BiomarkerKB VMs 

### ISSUE THREAD

**Issue by seankim658** [clinical-biomarkers/biomarker-issue-repo#49]
Sent an email to RTS with Miguel copied to setup a meeting to set up the port listeners and other VM configurations so Miguel can finish setting up the KG docker container.

**Comment by seankim658** [comment]
@MiguelMazumder Can you update this with the results from the call.

**Comment by MiguelMazumder** [comment]
Had a meeting with Dacian in order to set up Knowledge Graph on the BiomarkerKB servers due to firewall issues and set up port listening to get the Neo4j website UI to be functional. Setting up the bolt connection was successful and we are now able to make queries on the knowledge graph from any python script that has access to the bolt URI, username, and password. Unfortunately, so visualize these queries which would have been done on the UI side, Dacian believes it is either not possible or will take an extremely long time to implement due to the KG requiring a secure connection involving a certificate handshake. This isn't too bad because there are workarounds to visualize the output of these queries until we get the UI running

**Comment by seankim658** [comment]
Closing for now, @MiguelMazumder feel free to reopen if you feel its needed
